/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useEffect } from "react";

import { useAnimations, useGLTF } from "@react-three/drei";

const Model = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/boy.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.animation === true) {
      actions.moove.play();
    } else {
      actions.moove.stop();
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          material={materials.Boy01_Body_MAT}
          geometry={nodes.Boy01_Body_Geo.geometry}
          skeleton={nodes.Boy01_Body_Geo.skeleton}
        />
        <skinnedMesh
          material={materials.Boy01_Brows_MAT1}
          geometry={nodes.Boy01_Brows_Geo.geometry}
          skeleton={nodes.Boy01_Brows_Geo.skeleton}
        />
        <skinnedMesh
          material={materials.Boy01_Eyes_MAT1}
          geometry={nodes.Boy01_Eyes_Geo.geometry}
          skeleton={nodes.Boy01_Eyes_Geo.skeleton}
        />
        <skinnedMesh
          material={materials.Boy01_Mouth_MAT1}
          geometry={nodes.h_Geo.geometry}
          skeleton={nodes.h_Geo.skeleton}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/boy.glb");

export default Model;
